functionsDirectory = "C:\\Users\\admin\\OneDrive\\Desktop\\Claude\\ChatGPT\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "C:\\Users\\admin\\OneDrive\\Desktop\\Claude\\ChatGPT"
publishOrigin = "config"
functions = "C:\\Users\\admin\\OneDrive\\Desktop\\Claude\\ChatGPT\\netlify\\functions"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[functions]

  [functions."*"]
  included_files = [
    "backend/data/state.json"
  ]
  node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
force = true

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/"
to = "/carrier-database.html"
status = 200
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]